# Файл содержит свойства, используемые для всех профилей
server:
  port: 8082

spring:
  kafka:
    consumer:
      group-id: Kata.1
      bootstrap-servers: localhost:9092
    template:
      default-topic: fit-user
  #    producer:
#      acks: 1
#      retries: 3
#      transaction-id-prefix: FIT
  profiles:
    active: dev
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres_adm
    password: postgres_pass
  liquibase:
    enabled: true
    drop-first: false
    change-log: db/db.changelog-master.yaml
    default-schema: public
